# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui_simHKVDdk.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet(u"")
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 1920, 100))
        self.widget.setStyleSheet(u"background-color: rgb(238, 0, 51);")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 111, 31))
        font = QFont()
        font.setFamily(u"Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lb_map_name = QLabel(self.widget)
        self.lb_map_name.setObjectName(u"lb_map_name")
        self.lb_map_name.setGeometry(QRect(140, 10, 301, 31))
        self.lb_map_name.setFont(font)
        self.lb_map_name.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_number_robot = QLabel(self.widget)
        self.lb_number_robot.setObjectName(u"lb_number_robot")
        self.lb_number_robot.setGeometry(QRect(440, 50, 101, 31))
        self.lb_number_robot.setFont(font)
        self.lb_number_robot.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_number_robot.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(440, 10, 101, 31))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(540, 10, 131, 31))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.lb_num_station = QLabel(self.widget)
        self.lb_num_station.setObjectName(u"lb_num_station")
        self.lb_num_station.setGeometry(QRect(540, 50, 131, 31))
        self.lb_num_station.setFont(font)
        self.lb_num_station.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_num_station.setAlignment(Qt.AlignCenter)
        self.lb_runtime = QLabel(self.widget)
        self.lb_runtime.setObjectName(u"lb_runtime")
        self.lb_runtime.setGeometry(QRect(140, 50, 301, 31))
        self.lb_runtime.setFont(font)
        self.lb_runtime.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 50, 121, 31))
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(670, 10, 181, 31))
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.lb_pph_2 = QLabel(self.widget)
        self.lb_pph_2.setObjectName(u"lb_pph_2")
        self.lb_pph_2.setGeometry(QRect(670, 50, 181, 31))
        self.lb_pph_2.setFont(font)
        self.lb_pph_2.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_pph_2.setAlignment(Qt.AlignCenter)
        self.lb_pph_3 = QLabel(self.widget)
        self.lb_pph_3.setObjectName(u"lb_pph_3")
        self.lb_pph_3.setGeometry(QRect(860, 50, 181, 31))
        self.lb_pph_3.setFont(font)
        self.lb_pph_3.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_pph_3.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(860, 10, 181, 31))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.lb_pph_4 = QLabel(self.widget)
        self.lb_pph_4.setObjectName(u"lb_pph_4")
        self.lb_pph_4.setGeometry(QRect(1050, 50, 181, 31))
        self.lb_pph_4.setFont(font)
        self.lb_pph_4.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_pph_4.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1050, 10, 181, 31))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1240, 10, 181, 31))
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.lb_pph_5 = QLabel(self.widget)
        self.lb_pph_5.setObjectName(u"lb_pph_5")
        self.lb_pph_5.setGeometry(QRect(1240, 50, 181, 31))
        self.lb_pph_5.setFont(font)
        self.lb_pph_5.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_pph_5.setAlignment(Qt.AlignCenter)
        self.lb_num_thread = QLabel(self.widget)
        self.lb_num_thread.setObjectName(u"lb_num_thread")
        self.lb_num_thread.setGeometry(QRect(1710, 50, 201, 31))
        self.lb_num_thread.setFont(font)
        self.lb_num_thread.setStyleSheet(u"color: rgb(0, 255, 0);")
        self.lb_num_thread.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(1710, 10, 201, 31))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.wid_monitor = QWidget(self.centralwidget)
        self.wid_monitor.setObjectName(u"wid_monitor")
        self.wid_monitor.setGeometry(QRect(0, 105, 1920, 975))
        self.wid_monitor.setStyleSheet(u"background-color: rgb(181, 180, 180);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"B\u1ea3n \u0111\u1ed3", None))
        self.lb_map_name.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.lb_number_robot.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Robot", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Station", None))
        self.lb_num_station.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lb_runtime.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Runtime", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng k\u1ec7 nh\u1eadp", None))
        self.lb_pph_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lb_pph_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"T\u1ed5ng k\u1ec7 xu\u1ea5t", None))
        self.lb_pph_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"L\u01b0\u1ee3t nh\u1eadp / h", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"L\u01b0\u1ee3t xu\u1ea5t / h", None))
        self.lb_pph_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lb_num_thread.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Num of Thread", None))
    # retranslateUi

